apiVersion: v1
kind: ServiceAccount
metadata:
  name: kapinger-sa
  namespace: default
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: kapinger-role
  namespace: default
rules:
  - apiGroups: [""]
    resources: ["services", "pods"]
    verbs: ["get", "list"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: kapinger-rolebinding
  namespace: default
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: kapinger-role
subjects:
  - kind: ServiceAccount
    name: kapinger-sa
    namespace: default
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: kapinger
  namespace: default
spec:
  replicas: 2
  selector:
    matchLabels:
      app: kapinger
  template:
    metadata:
      labels:
        app: kapinger
    spec:
      serviceAccountName: kapinger-sa
      nodeSelector:
        "kubernetes.io/os": linux
      affinity:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
            - weight: 50
              podAffinityTerm:
                labelSelector:
                  matchExpressions:
                    - key: "app"
                      operator: In
                      values:
                        - kapinger
                topologyKey: "kubernetes.io/hostname"
      containers:
        - name: kapinger
          image: acnpublic.azurecr.io/kapinger:latest
          resources:
            limits:
              memory: 20Mi
            requests:
              memory: 20Mi
          env:
            - name: TARGET_TYPE
              value: "service"
            - name: POD_IP
              valueFrom:
                fieldRef:
                  fieldPath: status.podIP
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: HTTP_PORT
              value: "8080"
            - name: TCP_PORT
              value: "8085"
            - name: UDP_PORT
              value: "8086"
          ports:
            - containerPort: 8080

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: kapinger-win
  namespace: default
spec:
  replicas: 5
  selector:
    matchLabels:
      app: kapinger
  template:
    metadata:
      labels:
        app: kapinger
    spec:
      serviceAccountName: kapinger-sa
      nodeSelector:
        "kubernetes.io/os": windows
      affinity:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
            - weight: 100
              podAffinityTerm:
                labelSelector:
                  matchExpressions:
                    - key: "app"
                      operator: In
                      values:
                        - kapinger
                topologyKey: "kubernetes.io/hostname"
      containers:
        - name: kapinger
          image: acnpublic.azurecr.io/kapinger:windows-ltsc2022-amd64-v35
          env:
            - name: TARGET_TYPE
              value: "service"
            - name: POD_IP
              valueFrom:
                fieldRef:
                  fieldPath: status.podIP
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: HTTP_PORT
              value: "8080"
            - name: TCP_PORT
              value: "8085"
            - name: UDP_PORT
              value: "8086"
          ports:
            - containerPort: 8080

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: kapinger-drop
  namespace: default
spec:
  replicas: 0
  selector:
    matchLabels:
      app: kapinger-drop
  template:
    metadata:
      labels:
        app: kapinger-drop
    spec:
      serviceAccountName: kapinger-sa
      nodeSelector:
        "kubernetes.io/os": linux
      affinity:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
            - weight: 100
              podAffinityTerm:
                labelSelector:
                  matchExpressions:
                    - key: "app"
                      operator: In
                      values:
                        - kapinger
                topologyKey: "kubernetes.io/hostname"
      containers:
        - name: kapinger
          image: acnpublic.azurecr.io/kapinger:latest
          resources:
            limits:
              memory: 20Mi
            requests:
              memory: 20Mi
          env:
            - name: TARGET_TYPE
              value: "service"
            - name: POD_IP
              valueFrom:
                fieldRef:
                  fieldPath: status.podIP
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: HTTP_PORT
              value: "8080"
            - name: TCP_PORT
              value: "8085"
            - name: UDP_PORT
              value: "8086"
          ports:
            - containerPort: 8080

---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: deny-traffic-to-kapinger-drop
  namespace: default
spec:
  podSelector:
    matchLabels:
      app: kapinger-drop
  policyTypes:
    - Ingress
    - Egress
  ingress: []
  egress: []
---
apiVersion: v1
kind: Service
metadata:
  name: kapinger-service
  namespace: default
  labels:
    app: kapinger
spec:
  selector:
    app: kapinger
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
  type: ClusterIP
